import ast
import os
import sys
import inspect
from pathlib import Path
import json

# --- AGL PATH MANAGER ---
try:
    # Try importing as a module from root
    from AGL_Core.AGL_Paths import AGL_Path_Manager
    AGL_Path_Manager()
except ImportError:
    try:
        # Try importing locally if running from AGL_Core directory
        from AGL_Paths import AGL_Path_Manager
        AGL_Path_Manager()
    except ImportError:
        # Fallback manual setup
        current_dir = os.path.dirname(os.path.abspath(__file__))
        repo_copy_path = os.path.join(current_dir, '..', 'repo-copy')
        if repo_copy_path not in sys.path:
            sys.path.append(repo_copy_path)
# ------------------------

try:
    from Core_Engines.Hosted_LLM import chat_llm
    print("✅ Hosted_LLM imported successfully.")
except ImportError:
    print("⚠️ Hosted_LLM not found. Using mock generation.")
    chat_llm = None

class AGL_Auto_Documenter:
    """
    AGL Auto Documenter (The Scribe)
    
    Responsibilities:
    1. Scan the codebase for undocumented classes and functions.
    2. Generate precise docstrings using the AGL Intelligence (Hosted_LLM).
    3. Inject docstrings into the files (Self-Organization).
    4. Generate a comprehensive 'AGL_FINAL_SYSTEM_DOCUMENTATION.md'.
    """
    
    def __init__(self, root_dir):
        self.root_dir = Path(root_dir)
        self.ignore_dirs = {
            '.git', '__pycache__', 'venv', '.venv', 'env', 'node_modules', 'artifacts', 'backups', 'dist', 'build', 
            'ل', 'لا', 'venv_cv2', 'repo-copy-HILT-experiment', 'repo-copy_test_run.info', 'htmlcov', 'htmlcov_after_retriever_fix'
        }
        self.system_map = {}

    def generate_docstring(self, name, type_, code_snippet):
        """Generates a docstring using the LLM."""
        if not chat_llm:
            return f'"""\n        [Auto-Generated] {type_} {name}: Documentation placeholder.\n        """'
        
        prompt = [
            {"role": "system", "content": "You are the AGL System Architect. Your task is to write precise, professional Python docstrings (Google Style)."},
            {"role": "user", "content": f"Write a docstring for this {type_} named '{name}'.\n\nCode:\n{code_snippet}\n\nReturn ONLY the docstring content, no quotes."}
        ]
        
        try:
            response = chat_llm(prompt, max_new_tokens=200, temperature=0.3)
            # Clean up response
            doc = response.strip().replace('"""', '')
            return f'"""\n        {doc}\n        """'
        except Exception as e:
            print(f"Error generating docstring for {name}: {e}")
            return f'"""\n        [Error] Could not generate documentation.\n        """'

    def analyze_file(self, file_path):
        """Parses a file and returns its structure."""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            tree = ast.parse(content)
            
            structure = {
                'classes': [],
                'functions': [],
                'docstring': ast.get_docstring(tree)
            }
            
            for node in ast.walk(tree):
                if isinstance(node, ast.ClassDef):
                    structure['classes'].append({
                        'name': node.name,
                        'lineno': node.lineno,
                        'docstring': ast.get_docstring(node)
                    })
                elif isinstance(node, ast.FunctionDef):
                    structure['functions'].append({
                        'name': node.name,
                        'lineno': node.lineno,
                        'docstring': ast.get_docstring(node)
                    })
            
            return structure
        except Exception as e:
            print(f"Error parsing {file_path}: {e}")
            return None

    def build_system_report(self):
        """Scans the whole system and builds a report."""
        print(f"🔍 Scanning AGL System at {self.root_dir}...")
        
        report_lines = [
            "# 📘 AGL FINAL SYSTEM DOCUMENTATION",
            f"**Date:** {os.path.basename(str(self.root_dir))}",
            "**Status:** Auto-Generated by AGL_Auto_Documenter",
            "",
            "## 📂 Project Structure",
            ""
        ]
        
        for root, dirs, files in os.walk(self.root_dir):
            # Filter ignored dirs
            dirs[:] = [d for d in dirs if d not in self.ignore_dirs]
            
            for file in files:
                if file.endswith('.py'):
                    # Filter temporary and hidden files
                    if file.startswith('.') or file.startswith('tmp_') or file.startswith('temp_'):
                        continue
                    if file.startswith('_') and file != '__init__.py':
                        continue

                    file_path = Path(root) / file
                    rel_path = file_path.relative_to(self.root_dir)
                    
                    print(f"  - Analyzing {rel_path}...")
                    structure = self.analyze_file(file_path)
                    
                    if structure:
                        report_lines.append(f"### 📄 `{rel_path}`")
                        if structure['docstring']:
                            report_lines.append(f"> {structure['docstring'].strip().splitlines()[0]}")
                        report_lines.append("")
                        
                        if structure['classes']:
                            report_lines.append("**Classes:**")
                            for cls in structure['classes']:
                                doc_content = cls['docstring'].strip() if cls['docstring'] else ""
                                doc = doc_content.splitlines()[0] if doc_content else "*(No Documentation)*"
                                report_lines.append(f"- **`{cls['name']}`**: {doc}")
                        
                        if structure['functions']:
                            report_lines.append("\n**Functions:**")
                            for func in structure['functions']:
                                doc_content = func['docstring'].strip() if func['docstring'] else ""
                                doc = doc_content.splitlines()[0] if doc_content else "*(No Documentation)*"
                                report_lines.append(f"- **`{func['name']}`**: {doc}")
                        
                        report_lines.append("\n---\n")
        
        output_path = self.root_dir / "AGL_FINAL_SYSTEM_DOCUMENTATION.md"
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(report_lines))
        
        print(f"✅ Documentation generated at: {output_path}")
        return output_path

if __name__ == "__main__":
    # Default to current workspace root
    root = Path(r"d:\AGL")
    documenter = AGL_Auto_Documenter(root)
    documenter.build_system_report()
