import requests
import json
import time

# رابط السيرفر
URL = "http://127.0.0.1:8000/chat"

# قائمة المهام (كل مهمة تستهدف محركاً محدداً بالاسم)
TEST_CASES = [
    # 1. قطاع العلوم والرياضيات
    {"engine": "PhysicsSolver", "cmd": "Use PhysicsSolver to calculate force mass=10 acc=5"},
    {"engine": "ChemistrySolver", "cmd": "Use ChemistrySolver to describe H2O"},
    {"engine": "AlgebraSolver", "cmd": "Use AlgebraSolver to solve 2x + 4 = 10"},
    {"engine": "MathematicalBrain", "cmd": "Use MathematicalBrain to solve 5x = 25"},
    
    # 2. قطاع البرمجة (المسار السريع)
    {"engine": "CodeGenerator", "cmd": "اكتب كود بايثون يطبع جملة Hello AGL"},
    {"engine": "PythonSpecialist", "cmd": "Use PythonSpecialist to write a list comprehension example"},
    
    # 3. قطاع الأمان
    {"engine": "EmergencyDoctor", "cmd": "Run EmergencyDoctor scan"},
    {"engine": "ConsistencyChecker", "cmd": "Use ConsistencyChecker to validate logic"},
    
    # 4. قطاع التفكير والاستراتيجية
    {"engine": "StrategicThinking", "cmd": "Use StrategicThinking to plan a chess opening"},
    {"engine": "CausalGraph", "cmd": "Use CausalGraph to analyze rain and wet ground"},
    
    # 5. قطاع المجتمع والإبداع
    {"engine": "SocialInteraction", "cmd": "Use SocialInteraction to reply to a greeting"},
    {"engine": "HumorIronyStylist", "cmd": "Use HumorIronyStylist to tell a joke about Python"},
]

def run_diagnostics():
    print(f"🚀 STARTING SYSTEM DIAGNOSTICS [Target: {len(TEST_CASES)} Engines]...\n")
    print(f"{'ENGINE':<25} | {'STATUS':<10} | {'RESPONSE SNIPPET'}")
    print("-" * 70)
    
    success_count = 0
    
    for test in TEST_CASES:
        engine = test['engine']
        payload = {"message": test['cmd']}
        
        try:
            # قياس زمن الاستجابة
            start_time = time.time()
            response = requests.post(URL, json=payload, timeout=20)
            elapsed = time.time() - start_time
            
            if response.status_code == 200:
                data = response.json()
                reply = data.get("reply", "")
                meta = data.get("meta", {})
                
                # معايير النجاح:
                # 1. ظهور علامة البرق ⚡ (للمسار الشامل)
                # 2. أو ظهور توقيع Generated by (للمسار الهندسي)
                # 3. أو أن الميتا داتا تحتوي اسم المحرك
                
                is_alive = False
                if "⚡" in reply or "Generated by" in reply:
                    is_alive = True
                if meta.get("engine") == engine:
                    is_alive = True
                
                # تنظيف الرد للعرض
                clean_reply = reply.replace("\n", " ")[:40]
                
                if is_alive:
                    status = "✅ ONLINE"
                    success_count += 1
                else:
                    status = "⚠️ WEAK"
                
                print(f"{engine:<25} | {status:<10} | {clean_reply}...")
                
            else:
                print(f"{engine:<25} | ❌ ERROR  | HTTP {response.status_code}")
                
        except Exception as e:
            print(f"{engine:<25} | 💀 DEAD   | Connection Failed")

    print("-" * 70)
    print(f"\n📊 DIAGNOSTIC RESULT: {success_count}/{len(TEST_CASES)} Engines Responding Correctly.")

if __name__ == "__main__":
    run_diagnostics()
