import os
import ast
import sys

# Setup paths
SOURCE_FILE = r"d:\AGL\repo-copy\AGL_legacy.py"
OUTPUT_DIR = r"d:\AGL\repo-copy\Refactored_Legacy"

if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

def refactor_legacy_code():
    print(f"🔧 STARTING REFACTORING PROTOCOL FOR: {SOURCE_FILE}")
    
    with open(SOURCE_FILE, "r", encoding="utf-8") as f:
        source_code = f.read()
        
    tree = ast.parse(source_code)
    
    # 1. Extract Imports
    imports = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            imports.append(ast.get_source_segment(source_code, node))
            
    imports_block = "\n".join(imports)
    
    # 2. Find the Monolith Class (AGL)
    agl_class = None
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == "AGL":
            agl_class = node
            break
            
    if not agl_class:
        print("❌ Critical Error: Class 'AGL' not found in legacy file.")
        return

    print(f"   -> Found Monolith Class 'AGL' with {len(agl_class.body)} nodes.")
    
    # 3. Categorize Methods
    categories = {
        "Risk": [],
        "Learning": [],
        "Operation": [],
        "Core": []
    }
    
    for node in agl_class.body:
        if isinstance(node, ast.FunctionDef):
            code = ast.get_source_segment(source_code, node)
            name = node.name.lower()
            
            if "risk" in name or "confidence" in name or "security" in name:
                categories["Risk"].append(code)
            elif "learn" in name or "train" in name or "knowledge" in name:
                categories["Learning"].append(code)
            elif "run" in name or "execute" in name or "process" in name or "operation" in name:
                categories["Operation"].append(code)
            else:
                categories["Core"].append(code)
                
    # 4. Generate Component Files
    for cat, methods in categories.items():
        if not methods:
            continue
            
        filename = f"AGL_Legacy_{cat}.py"
        filepath = os.path.join(OUTPUT_DIR, filename)
        
        class_name = f"AGL_{cat}_Mixin"
        
        content = f"""# Refactored {cat} Component from AGL_legacy.py
# Auto-generated by AGL Refactoring Protocol

{imports_block}

class {class_name}:
    \"\"\"
    Extracted {cat} logic from the original monolith.
    \"\"\"
"""
        # Indent methods to fit inside class
        for method in methods:
            indented_method = "\n    ".join(method.splitlines())
            content += f"\n    {indented_method}\n"
            
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
            
        print(f"   ✅ Generated: {filename} ({len(methods)} methods)")

    # 5. Generate the New Main Class (Inheriting from Mixins)
    main_file = os.path.join(OUTPUT_DIR, "AGL_Refactored_Main.py")
    
    mixin_imports = "\n".join([f"from .AGL_Legacy_{cat} import AGL_{cat}_Mixin" for cat in categories if categories[cat]])
    mixin_inheritance = ", ".join([f"AGL_{cat}_Mixin" for cat in categories if categories[cat]])
    
    main_content = f"""# AGL Refactored Main Entry Point
# Auto-generated by AGL Refactoring Protocol

{imports_block}
{mixin_imports}

class AGL_Refactored({mixin_inheritance}):
    \"\"\"
    The Modernized AGL System.
    Inherits capabilities from specialized mixins to reduce cognitive load (Dissonance).
    \"\"\"
    
    def __init__(self, operational_mode: str = "supervised_autonomy", config: Optional[dict] = None):
        super().__init__()
        self.config = config or {{}}
        print("🚀 AGL Refactored System Initialized (Low Dissonance Mode)")

    # Original Init logic should be migrated here or called via super
"""
    with open(main_file, "w", encoding="utf-8") as f:
        f.write(main_content)
        
    print(f"   ✅ Generated: AGL_Refactored_Main.py")
    print("\n🎉 REFACTORING COMPLETE. Dissonance resolved.")

if __name__ == "__main__":
    refactor_legacy_code()
