# Generated by AGL Self-Engineer
# Module: logger_utility

import logging
from typing import Any


def get_task_logger(task_name: str) -> logging.Logger:
    """Return a configured logger for `task_name`.

    The setup is idempotent: handlers are only added when the logger
    has no handlers yet. `propagate` is disabled to avoid duplicate
    messages when a root logger is configured elsewhere.
    """
    logger = logging.getLogger(task_name)
    # Only add handlers if none exist to avoid duplicate outputs
    if not logger.handlers:
        handler = logging.StreamHandler()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        logger.addHandler(handler)

    logger.setLevel(logging.DEBUG)
    logger.propagate = False
    return logger


def run_task(task_name: str, message: Any) -> None:
    """Log `message` under `task_name`.

    This is a thin wrapper around the configured logger. Avoids adding
    duplicate handlers on repeated calls or inside loops.
    """
    logger = get_task_logger(task_name)
    logger.info(message)