# D:\AGL\repo-copy\Integration_Layer\AGI_Expansion.py
import re

class SmartRouterExtension:
    """
    طبقة التوسعة الذكية (Smart Extension Layer)
    وظيفتها: اعتراض الطلبات السريعة (مثل الكود) ومعالجتها فوراً،
    وترك الباقي للنظام القديم.
    """
    def __init__(self):
        # كلمات مفتاحية تدل على طلب برمجي صريح
        self.code_keywords = ["write code", "python script", "function to", "اكتب كود", "برنامج بايثون", "دالة"]

    def is_fast_task(self, user_input: str) -> bool:
        """هل هذا الطلب يحتاج للمسار السريع؟"""
        text = user_input.lower()

        # Any explicit code keywords
        if any(kw in text for kw in self.code_keywords):
            return True

        # Strict instructional patterns (e.g., natural language prompts generated by self-engineer)
        strict_indicators = ["strict instruction", "wrap code", "output only", "python module", "run_task"]
        if any(indicator in text for indicator in strict_indicators):
            return True

        # Detect code block requests (markdown or emphasis)
        if "```python" in user_input or "```" in user_input:
            return True

        return False

    def generate_fast_code(self, user_input: str) -> str:
        """
        توليد برومبت صارم للموديل لكي يكتب الكود فقط.
        """
        system_prompt = (
            "IDENTITY: You are an Expert Python Coder (AGL Engineering Core).\n"
            "RULE: Output ONLY valid Python code inside markdown blocks.\n"
            "RULE: NO explanations. NO conversational filler.\n"
        )
        return f"{system_prompt}\nREQUEST: {user_input}\nCODE:"

# إنشاء نسخة جاهزة للاستخدام
expansion_layer = SmartRouterExtension()
